name: MediaFlow Proxy CI/CD

on:
  release:
    types: [ created ]

jobs:
  mediaflow_proxy_docker_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: mhdzumair
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mhdzumair/mediaflow-proxy:v${{ github.ref_name }}
            mhdzumair/mediaflow-proxy:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
